name: CI/CD Pipeline NP1 - Finance App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    name: Execução de Testes
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Rodar Testes Unitários
        run: mvn test

      - name: Salvar Relatório de Testes (Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports/


  build:
    name: Build e Empacotamento
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Setup Java 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Gerar Pacote JAR
        run: mvn package -DskipTests

      - name: Salvar JAR (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: finance-app-jar
          path: target/*.jar


  deploy:
    name: Deploy Automático
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      - name: Simulação de Deploy
        run: |
          echo "Realizando deploy do pacote Java 22..."
          mkdir -p deploy_folder
          echo "Deploy concluído" > deploy_folder/status.txt


  notification:
    name: Notificação por E-mail
    runs-on: ubuntu-latest
    needs: [tests, build, deploy]
    if: always()
    steps:
      - name: Enviar E-mail de Status
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: ${{ secrets.EMAIL_DESTINO }}
          from: "GitHub Pipeline <${{ secrets.MAIL_USERNAME }}>"
          subject: "Status Final da Pipeline NP1"
          body: |
            A execução da pipeline foi finalizada.
            
            RESULTADOS:
            - Testes: ${{ needs.tests.result }}
            - Build: ${{ needs.build.result }}
            - Deploy: ${{ needs.deploy.result }}